### ISSUE TITLE
Adding an indicator for short-term development

### ISSUE THREAD

**Issue by emk2203** [trackercli/covid19-tracker-cli#23]
It would be good to have the percentage change relative to last week. That can tell if a country is on the right path.

Maybe a line like:

Δ% - last week X% - two weeks ago Y% - a month ago Z%

I think that's really helpful. The history graph is nice eye candy, but too coarse to draw conclusions.

**Comment by WarenGonzaga** [comment]
@emk2203 thank you we will take a look on this...

**Comment by WarenGonzaga** [comment]
@emk2203 we have implemented the history chart... I guess that's enough for a moment.
