### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by jerch** [trackercli/covid19-tracker-cli#34]
I really appreciate the work you did, many thx.

Ofc as a terminal dev I cannot avoid to do some blaming as well. Here is the problem:

**Never ever encourage ppl to input downloaded stuff unchecked in the terminal!** 

I am sure you did this with good intentions and your data is free of malicious actions, but plz lets not spread a bad habit. We all better ban any command combination in the form `curl -L ...` or `curl ... | bash` from our memory. It opens the door for trojans and viruses (thus it is in a weird way ontopic).

*How should this be done instead?*
Well, write a tiny data parser (maybe JSON), that can actually validate the content before putting it onto the terminal. This still can be driven by a simple curl command, but is actually safe if the parser does the proper checks: `curl .... | tiny_parser`

In the meantime - stay safe, and to anyone who already got infected - get well soon!

**Comment by WarenGonzaga** [comment]
@jerch thank you for letting us know... we will consider this...

**Comment by WarenGonzaga** [comment]
@jerch closing this...
