### ISSUE TITLE
wget example

### ISSUE THREAD

**Issue by gilcot** [trackercli/covid19-tracker-cli#43]
To be similar with `curl` and `httpie` example, i.e. no intermediate file but stdout, replace
```shell
wget -i https://covid19.trackercli.com && cat index.html
```
with the following (asking to use stdout as output file)
```shell
wget -i -O - https://covid19.trackercli.com
```
Best regards.

**Comment by WarenGonzaga** [comment]
Hi @gilcot sorry for the late reply... your suggestion might be the best idea... we'll look into this.

**Comment by spmfox** [comment]
Created a pull request to address this, https://github.com/trackercli/covid19-tracker-cli/pull/52.

**Comment by WarenGonzaga** [comment]
Closing this now...
