### ISSUE TITLE
Option for hiding irrelevant info to the actual stats

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [trackercli/covid19-tracker-cli#47]
Consider adding an option for hiding support etc info, similar to chubin/wttr.in's superquiet format.

At the moment, the output of a basic curl gets an "advert" about the third of the length of the whole output at the end.

**Comment by WarenGonzaga** [comment]
Good idea! We will take a look into it.

**Comment by WarenGonzaga** [comment]
@R0LA1mRifcF8yAkk I can only remove the unnecessary info in the project. I'm afraid I can't hide the support and donation info. What I suggest is to coordinate with us and we will give you dedicated URL with no support and ads. Join to our discord server.

**Comment by R0LA1mRifcF8yAkk** [comment]
I'm sorry, I won't be joining the discord server. I believe this matter can be solved here. Also I'm sorry if some of the following sounds hostile, it is not intended to be.

I'd hazard a guess that if it's possible to give me a customized URL, it should be possible to toggle the same behavior with a URL parameter.

What do you mean by not being able to remove certain info? Don't you have control over the whole output? What if a person is already a donator and they want to disable the donation prompt?

Is there a technical blocker so the output can't be modified? Or is it a matter of principle? That is, you wish to always let the user know: where the data is taken from; where the source code can be found; a randomly selected message from the author; a donation prompt; and finally, a Twitter handle to follow the author?

I'd say probably most daily users could do without at least the stuff after the table. I, personally, would like to see just the table, without the last 3 rows (help, data source, source code), so just the pure data.

**Comment by WarenGonzaga** [comment]
Hi @R0LA1mRifcF8yAkk the answer is here #48

**Comment by R0LA1mRifcF8yAkk** [comment]
That sounds good enough. However I might have come across, I do appreciate the work being done here, thank you.
