### ISSUE TITLE
Feature Request: Browser Support

### ISSUE THREAD

**Issue by jkga** [trackercli/covid19-tracker-cli#55]
Support for displaying dashboard in the browser like `wttr`

**Sample Request: https://wttr.in/**
**Reponse:** 
![image](https://user-images.githubusercontent.com/10413754/103149674-8cf5e300-47a6-11eb-91a2-dbc3658407b5.png)

**Comment by WarenGonzaga** [comment]
@jkga can you do it?

**Comment by jkga** [comment]
yes, you can visit this [link](https://covid19-tracker-cli-21t7uvea5.vercel.app/history/web/charts/us) to see how it looks like @WarenGonzaga. However, there is still no geo location feature so the visitor must explicitly identify their country of origin.

**PARAMS**
- :country (*required)
- :size (sm/md/lg *optional)
https://covid19-tracker-cli-21t7uvea5.vercel.app/history/web/charts/:country/:size

**Comment by WarenGonzaga** [comment]
What if we add default location something like Philippines.

**Comment by jkga** [comment]
yes, we can do that..

**Comment by WarenGonzaga** [comment]
> yes, we can do that..

Let's do it! PR lang

**Comment by WarenGonzaga** [comment]
Merged I'm gonna close this.
